version: "3"

services:
  api:
    build: .
    volumes:
      - ".:/app"
    # - '.site-packages:/usr/local/lib/python3.10/site-packages'
    ports:
      - "8000:8000"
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes: 
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql





